/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gddzjdlofdzlcuybyoxf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkZHpqZGxvZmR6bGN1eWJ5b3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMjA3MjksImV4cCI6MjA4Nzc5NjcyOX0.cqS43HgsPmRW-2bKm-BYR4vIGONKjqdvwy5ZBcFi0DM"